"""Added raw_address column

Revision ID: 960e9da7431b
Revises: 
Create Date: 2021-04-22 16:27:30.414663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960e9da7431b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('raw_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'raw_address')
    # ### end Alembic commands ###
