export type ActionType =
  | 'GET_CONSTANTS'
  | 'GET_CONSTANTS_FAILED'
  | 'GET_CONSTANTS_SUCCEEDED'
  | 'GET_LISTING'
  | 'GET_LISTING_FAILED'
  | 'GET_LISTING_SUCCEEDED'
  | 'GET_ALL_LISTINGS'
  | 'GET_ALL_LISTINGS_FAILED'
  | 'GET_ALL_LISTINGS_SUCCEEDED'
  | 'SET_PAGE';
