"""Removed unique validation on the address of the listing

Revision ID: 269b05b89d39
Revises: fc4b2ca55cdf
Create Date: 2021-09-05 22:34:57.682536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269b05b89d39'
down_revision = 'fc4b2ca55cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('listing_address_key', 'listing', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('listing_address_key', 'listing', ['address'])
    # ### end Alembic commands ###
