"""Convert sheriff_sale.upset_amount and judgment to floats and removed address_sanitzed

Revision ID: 9719088e2f69
Revises: c9cdc29b98bf
Create Date: 2021-04-02 22:18:14.832155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9719088e2f69'
down_revision = 'c9cdc29b98bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('county_clerk', 'rowid', existing_type=sa.VARCHAR(), type_=sa.Integer(), existing_nullable=True)
    op.alter_column('sheriff_sale', 'judgment', existing_type=sa.VARCHAR(), type_=sa.Float(), existing_nullable=True)
    op.alter_column(
        'sheriff_sale', 'upset_amount', existing_type=sa.VARCHAR(), type_=sa.Float(), existing_nullable=True
    )
    op.drop_column('sheriff_sale', 'address_sanitized')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheriff_sale', sa.Column('address_sanitized', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column(
        'sheriff_sale', 'upset_amount', existing_type=sa.Float(), type_=sa.VARCHAR(), existing_nullable=True
    )
    op.alter_column('sheriff_sale', 'judgment', existing_type=sa.Float(), type_=sa.VARCHAR(), existing_nullable=True)
    op.alter_column('county_clerk', 'rowid', existing_type=sa.Integer(), type_=sa.VARCHAR(), existing_nullable=True)
    # ### end Alembic commands ###
