"""Added created/updated_on to sheriffsalemodel

Revision ID: a5afa0253cdd
Revises: 
Create Date: 2021-04-13 21:40:49.505045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5afa0253cdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sheriff_sale', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True)
    )
    op.add_column(
        'sheriff_sale', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheriff_sale', 'updated_on')
    op.drop_column('sheriff_sale', 'created_on')
    # ### end Alembic commands ###
