"""Added properties to CountyClerkModel

Revision ID: c9cdc29b98bf
Revises: 
Create Date: 2021-03-24 00:01:32.281476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9cdc29b98bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sheriff-sale')
    op.add_column('county_clerk', sa.Column('book', sa.Integer(), nullable=True))
    op.add_column('county_clerk', sa.Column('page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('county_clerk', 'page')
    op.drop_column('county_clerk', 'book')
    op.create_table('sheriff-sale',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"sheriff-sale_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('sheriff_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_sanitized', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attorney', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attorney_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('county', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('court_case', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deed', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deed_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('defendant', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('judgment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('maps_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parcel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plaintiff', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priors', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sale_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('secondary_unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unit_secondary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upset_amount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sheriff-sale_pkey'),
    sa.UniqueConstraint('address', name='sheriff-sale_address_key')
    )
    # ### end Alembic commands ###
