"""Added a property_id column to listing table

Revision ID: fc4b2ca55cdf
Revises: 960e9da7431b
Create Date: 2021-04-25 14:05:16.996511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4b2ca55cdf'
down_revision = '960e9da7431b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('property_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'property_id')
    # ### end Alembic commands ###
